language: c

os: linux
dist: trusty


before_install:
  -  sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  -  sudo apt-get update -q
  -  sudo apt-get install gcc-arm-embedded -y


script:
  -  bash ./.ci-build.sh
